name: package

on:
  push:
  release:
    types: [published]


jobs:
    build-package:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v3
          with:
              python-version: 3.9
        - name: Build pip package
          run: |
              pip install -U pip build
              python3 -m build --sdist --wheel --outdir dist/ .
        - name: Archive Pypi artifacts
          uses: actions/upload-artifact@v3
          with:
              name: pypi_dist
              path: dist
        - name: Publish package
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.TWINE_PROD_PASSWORD }}
